version: '3.8'

services:
  app:
    image: rippfball56/patient-appointment-booking:latest
    ports:
      - "3000:3000"
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - API_KEY=${API_KEY}
      - DATABASE_ID=${DATABASE_ID}
      - PATIENT_COLLECTION_ID=${PATIENT_COLLECTION_ID}
      - DOCTOR_COLLECTION_ID=${DOCTOR_COLLECTION_ID}
      - APPOINTMENT_COLLECTION_ID=${APPOINTMENT_COLLECTION_ID}
      - NEXT_PUBLIC_BUCKET_ID=${NEXT_PUBLIC_BUCKET_ID}
      - NEXT_PUBLIC_ENDPOINT=${NEXT_PUBLIC_ENDPOINT}
      - NEXT_PUBLIC_ADMIN_PASSKEY=${NEXT_PUBLIC_ADMIN_PASSKEY}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_SENDER_EMAIL=${SENDGRID_SENDER_EMAIL}
    restart: unless-stopped
